/****** Object:  Table [dbo].[SIG_ESTADOS]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SIG_ESTADOS](
	[ID_ESTADO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[EXT_GEOGRAFICA] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ID_ESTADO] PRIMARY KEY CLUSTERED 
(
	[ID_ESTADO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[SIG_ESTADOS] ([ID_ESTADO], [NOMBRE], [EXT_GEOGRAFICA]) VALUES (1, N'OAXACA', N'93757')
/****** Object:  Table [dbo].[TIPOS_DE_RIESGO]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TIPOS_DE_RIESGO](
	[ID] [int] NOT NULL,
	[CAT_NOMBRE] [varchar](100) NOT NULL,
	[CAT_DESCRIP] [text] NOT NULL,
 CONSTRAINT [PD_ID_TIPO_RIESGO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SIG_USERS]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SIG_USERS](
	[Id_Usuario] [int] NOT NULL,
	[user_name] [varchar](50) NOT NULL,
	[user_level] [int] NOT NULL,
	[user_password] [varchar](20) NOT NULL,
 CONSTRAINT [PK_USERS_ID] PRIMARY KEY CLUSTERED 
(
	[Id_Usuario] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SIG_REGIONES]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SIG_REGIONES](
	[ID_REGION] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[EXT_GEOGRAFICA] [varchar](100) NOT NULL,
	[ID_ESTADO] [int] NOT NULL,
 CONSTRAINT [PK_ID_REGION] PRIMARY KEY CLUSTERED 
(
	[ID_REGION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[SIG_REGIONES] ([ID_REGION], [NOMBRE], [EXT_GEOGRAFICA], [ID_ESTADO]) VALUES (1, N'Sierra Sur', N'15493', 1)
INSERT [dbo].[SIG_REGIONES] ([ID_REGION], [NOMBRE], [EXT_GEOGRAFICA], [ID_ESTADO]) VALUES (2, N'Sierra Norte', N'8972', 1)
INSERT [dbo].[SIG_REGIONES] ([ID_REGION], [NOMBRE], [EXT_GEOGRAFICA], [ID_ESTADO]) VALUES (3, N'Valle Central', N'9480', 1)
INSERT [dbo].[SIG_REGIONES] ([ID_REGION], [NOMBRE], [EXT_GEOGRAFICA], [ID_ESTADO]) VALUES (4, N'Mixteca', N'15671.08', 1)
INSERT [dbo].[SIG_REGIONES] ([ID_REGION], [NOMBRE], [EXT_GEOGRAFICA], [ID_ESTADO]) VALUES (5, N'Papaloapan', N'8496.79', 1)
INSERT [dbo].[SIG_REGIONES] ([ID_REGION], [NOMBRE], [EXT_GEOGRAFICA], [ID_ESTADO]) VALUES (6, N'Costa', N'11605.06', 1)
INSERT [dbo].[SIG_REGIONES] ([ID_REGION], [NOMBRE], [EXT_GEOGRAFICA], [ID_ESTADO]) VALUES (7, N'Cañada', N'4398.61', 1)
INSERT [dbo].[SIG_REGIONES] ([ID_REGION], [NOMBRE], [EXT_GEOGRAFICA], [ID_ESTADO]) VALUES (8, N'Istmo', N'20755.26', 1)
/****** Object:  Table [dbo].[SIG_CAT_RIESGOS]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SIG_CAT_RIESGOS](
	[ID_CAT_RIESGO] [int] NOT NULL,
	[ID_TIPO_RIESGO] [int] NOT NULL,
	[NOMBRE_CATEORIA] [varchar](50) NOT NULL,
	[DESC_CATEGORIA] [varchar](255) NOT NULL,
	[NIVEL_RIESGO] [int] NOT NULL,
 CONSTRAINT [PK_CAT_RIESGO] PRIMARY KEY CLUSTERED 
(
	[ID_CAT_RIESGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SIG_DISTRITOS]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SIG_DISTRITOS](
	[ID_DISTRITO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[COORDENADAS] [varchar](100) NOT NULL,
	[ID_REGION] [int] NOT NULL,
	[EXT_GEOGRAFICA] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ID_DISTRITOS] PRIMARY KEY CLUSTERED 
(
	[ID_DISTRITO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (1, N'Silacayoapam', N'1.30.40', 4, N'1830.54')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (2, N'Huajuapan', N'1.30.40', 4, N'3269.74')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (3, N'Coixtlahuaca', N'1.30.40', 4, N'1666.19')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (4, N'Teotitlán', N'1.30.40', 7, N'2211.67')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (5, N'Cuicatlán', N'1.30.40', 7, N'2186.94')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (6, N'Tuxtepec', N'1.30.40', 5, N'5495.74')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (7, N'Choapan', N'1.30.40', 5, N'3001.05')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (8, N'Juxtlahuaca', N'1.30.40', 4, N'1848.48')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (9, N'Teposcolula', N'1.30.40', 4, N'1546.57')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (10, N'Nochixtlán', N'1.30.40', 4, N'2798.69')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (11, N'Etla', N'1.30.40', 3, N'2220.96')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (12, N'Ixtlán', N'1.30.40', 2, N'2885.54')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (13, N'Villa Alta', N'1.30.40', 2, N'1156.39')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (14, N'Mixe', N'1.30.40', 2, N'4930.46')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (15, N'Putla', N'1.30.40', 2, N'2626.56')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (16, N'Tlaxiaco', N'1.30.40', 4, N'2710.87')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (17, N'Zaachila', N'1.30.40', 3, N'568.9')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (18, N'Zimatlán', N'1.30.40', 3, N'988.49')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (19, N'Centro', N'1.30.40', 3, N'538.6')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (20, N'Tlacolula', N'1.30.40', 3, N'3324.14')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (21, N'Jamiltepec', N'1.30.40', 6, N'4293.23')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (22, N'Juquila', N'1.30.40', 6, N'3538.54')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (23, N'Sola de Vega', N'1.30.40', 1, N'3592.42')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (24, N'Ejutla', N'1.30.40', 3, N'980.99')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (25, N'Ocotlán', N'1.30.40', 3, N'857.92')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (26, N'Miahuatlán', N'1.30.40', 1, N'3975.12')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (27, N'Yautepec', N'1.30.40', 1, N'4559.16')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (28, N'Tehuantepec', N'1.30.40', 8, N'6318.4')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (29, N'Juchitán', N'1.30.40', 8, N'14436.86')
INSERT [dbo].[SIG_DISTRITOS] ([ID_DISTRITO], [NOMBRE], [COORDENADAS], [ID_REGION], [EXT_GEOGRAFICA]) VALUES (30, N'Pochutla', N'1.30.40', 6, N'3773.29')
/****** Object:  Table [dbo].[SIG_MUNICIPIOS]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SIG_MUNICIPIOS](
	[ID_MUNICIPIOS] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[ID_DISTRITO] [int] NOT NULL,
	[EXT_GEOGRAFICA] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ID_MUNICIPIO] PRIMARY KEY CLUSTERED 
(
	[ID_MUNICIPIOS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SIG_POBLADOS]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SIG_POBLADOS](
	[ID_POBLADO] [int] NOT NULL,
	[ID_MUNICIPIO] [int] NOT NULL,
	[NOMBRE] [varchar](100) NOT NULL,
	[EXT_GEOFRAFICA] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ID_POBLADO] PRIMARY KEY CLUSTERED 
(
	[ID_POBLADO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ACONTECIMIENTOS-FENOMENOS]    Script Date: 12/14/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[ACONTECIMIENTOS-FENOMENOS](
	[ID_FENOMENO] [int] NOT NULL,
	[ID_CATEG_FENOMENO] [int] NOT NULL,
	[COORD_SUCESO] [varchar](100) NOT NULL,
	[ID_POBLADO] [int] NOT NULL,
	[C.P.] [varchar](30) NOT NULL,
	[FECHA_HORA_FENOMENO] [datetime] NOT NULL,
 CONSTRAINT [PK_ID_FENOMENO] PRIMARY KEY CLUSTERED 
(
	[ID_FENOMENO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  ForeignKey [FK_ID_ESTADO]    Script Date: 12/14/2017 12:39:51 ******/
ALTER TABLE [dbo].[SIG_REGIONES]  WITH CHECK ADD  CONSTRAINT [FK_ID_ESTADO] FOREIGN KEY([ID_ESTADO])
REFERENCES [dbo].[SIG_ESTADOS] ([ID_ESTADO])
GO
ALTER TABLE [dbo].[SIG_REGIONES] CHECK CONSTRAINT [FK_ID_ESTADO]
GO
/****** Object:  ForeignKey [FK_TIPO_RIESGO]    Script Date: 12/14/2017 12:39:51 ******/
ALTER TABLE [dbo].[SIG_CAT_RIESGOS]  WITH CHECK ADD  CONSTRAINT [FK_TIPO_RIESGO] FOREIGN KEY([ID_TIPO_RIESGO])
REFERENCES [dbo].[TIPOS_DE_RIESGO] ([ID])
GO
ALTER TABLE [dbo].[SIG_CAT_RIESGOS] CHECK CONSTRAINT [FK_TIPO_RIESGO]
GO
/****** Object:  ForeignKey [FK_ID_REGION]    Script Date: 12/14/2017 12:39:51 ******/
ALTER TABLE [dbo].[SIG_DISTRITOS]  WITH CHECK ADD  CONSTRAINT [FK_ID_REGION] FOREIGN KEY([ID_REGION])
REFERENCES [dbo].[SIG_REGIONES] ([ID_REGION])
GO
ALTER TABLE [dbo].[SIG_DISTRITOS] CHECK CONSTRAINT [FK_ID_REGION]
GO
/****** Object:  ForeignKey [FK_ID_DISTRITO]    Script Date: 12/14/2017 12:39:51 ******/
ALTER TABLE [dbo].[SIG_MUNICIPIOS]  WITH CHECK ADD  CONSTRAINT [FK_ID_DISTRITO] FOREIGN KEY([ID_DISTRITO])
REFERENCES [dbo].[SIG_DISTRITOS] ([ID_DISTRITO])
GO
ALTER TABLE [dbo].[SIG_MUNICIPIOS] CHECK CONSTRAINT [FK_ID_DISTRITO]
GO
/****** Object:  ForeignKey [FK_ID_MUNICIPIO]    Script Date: 12/14/2017 12:39:51 ******/
ALTER TABLE [dbo].[SIG_POBLADOS]  WITH CHECK ADD  CONSTRAINT [FK_ID_MUNICIPIO] FOREIGN KEY([ID_MUNICIPIO])
REFERENCES [dbo].[SIG_MUNICIPIOS] ([ID_MUNICIPIOS])
GO
ALTER TABLE [dbo].[SIG_POBLADOS] CHECK CONSTRAINT [FK_ID_MUNICIPIO]
GO
/****** Object:  ForeignKey [FK_ID_CATEG_FENOMENO]    Script Date: 12/14/2017 12:39:51 ******/
ALTER TABLE [dbo].[ACONTECIMIENTOS-FENOMENOS]  WITH CHECK ADD  CONSTRAINT [FK_ID_CATEG_FENOMENO] FOREIGN KEY([ID_CATEG_FENOMENO])
REFERENCES [dbo].[SIG_CAT_RIESGOS] ([ID_CAT_RIESGO])
GO
ALTER TABLE [dbo].[ACONTECIMIENTOS-FENOMENOS] CHECK CONSTRAINT [FK_ID_CATEG_FENOMENO]
GO
/****** Object:  ForeignKey [FK_ID_POBLADO]    Script Date: 12/14/2017 12:39:51 ******/
ALTER TABLE [dbo].[ACONTECIMIENTOS-FENOMENOS]  WITH CHECK ADD  CONSTRAINT [FK_ID_POBLADO] FOREIGN KEY([ID_POBLADO])
REFERENCES [dbo].[SIG_POBLADOS] ([ID_POBLADO])
GO
ALTER TABLE [dbo].[ACONTECIMIENTOS-FENOMENOS] CHECK CONSTRAINT [FK_ID_POBLADO]
GO
